before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: et618IWaXaPDco/Ow2FwIkg0x74cI9AhLfRO+AELl1Vi97MPYplrKJdbxjGzwCYdSgxfxDn9wt30tR7JryUe7UG90MH5GsmdJP3RlNvJRPWdB0/ysjgEBDMHJ6Ual1F0huMtv1RyFWXNSQwg++HZi7XsgVr3yAOt4y/oYJYDJUFD0QgcCOZlaKXrP72zN+HXla5A9Pl5o9aG/rAyZMmyNChZdFr32eVpcoGs/peFr+SSvUecDYAQtV1OI+ZmR9kexn0V2auXcKXTk+YhEFiez6b+Jw+hm37HXrn8/Am2ShEXkzSatAFC5Pb48vCkw+thu6u00GJmNrJyDbPsBXaLG7yKBV6pnMLxzf9zBFgd2qUCG+7O+LkrIN/78fNqumC7P7ILHDCIKAakOfDIBl9ayCUdfPeGyUga4bhL8ldh22j+6vc9P/TnBTFN6QVrRSlomMDSr8HTXmZ28IscLWYDIjzEp9oaPdMpPKy/rO9kbhNm4ZwrH/N49mwuICoUQ8q3b+i/O2UEiukpJ7HQt3Y2Q2q2L6W47TyngvmW+khz1ktl5Q/eMD73mrRS66DDqRYd2h8MgMP7kvQByv88otcFGs2Yc/Xy03AmR+qIluR0q9f6CnHCnFxh/tpemGMHx2yVl3ZmKelKwxvXUhX+sOPpy/ZTnB4ZLGnQcrWpNIkZvu0= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
